import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './provider'
import Navbar from './(components)/navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='light no-scrollbar' style={{colorScheme : 'light'}}>
      <body className={inter.className}>
        <Provider>
          <header></header>
          <main>{children}</main>
          <footer></footer> 
        </Provider>
        </body>
    </html>
  )
}
